protocol: "tcp"
regions: {
    addresses: "131.180.125.40",
    addresses: "131.180.125.41",
    client_addresses: "131.180.125.41",
    num_replicas: 1,
}
regions: {
    addresses: "131.180.125.42",
    addresses: "131.180.125.57",
    client_addresses: "131.180.125.42",
    num_replicas: 1,
}

movr_partitioning {
    cities: 1000
}
execution_type: MOVR

broker_ports: 2020
server_port: 2021
sequencer_port: 2022
forwarder_port: 2023

bypass_mh_orderer: false
mh_orderer_batch_duration: 5

num_log_managers: 2
num_partitions: 2
num_workers: 3

sequencer_batch_duration: 5

enabled_events: ALL