protocol: "tcp"
regions: {
    addresses: "131.180.125.40",
    addresses: "131.180.125.41",
    client_addresses: "131.180.125.41",
    num_replicas: 1,
}
regions: {
    addresses: "131.180.125.42",
    addresses: "131.180.125.57",
    client_addresses: "131.180.125.42",
    num_replicas: 1,
}
num_partitions: 2

# Workload
pps_partitioning {
    products: 25000000
    parts: 50000000
    suppliers: 25000000
    parts_per_product_max_regions: 2
    parts_per_product_max_partitions: 2
}
execution_type: PPS

# Broker
broker_ports: 2020

# Server
server_port: 2021

# Forwarder
forwarder_port: 2022
bypass_mh_orderer: true
fs_latency_interval: 200
avg_latency_window_size: 10
synchronized_batching: true
timestamp_buffer_us: 2000

# Sequencer
sequencer_port: 2023
sequencer_batch_duration: 5

# Log Manager
num_log_managers: 2

# Scheduler
num_workers: 3
ddr_interval: 100

enabled_events: ALL
