protocol: "tcp"
regions: {
    addresses: "10.0.1.213",
    addresses: "10.0.1.89",
    addresses: "10.0.1.49",
    addresses: "10.0.1.55",
    public_addresses: "54.176.113.172",
    public_addresses: "18.145.178.118",
    public_addresses: "52.53.130.198",
    public_addresses: "54.67.139.72",
    client_addresses: "13.57.188.59",
    num_replicas: 1,
}
regions: {
    addresses: "10.0.1.51",
    addresses: "10.0.1.126",
    addresses: "10.0.1.236",
    addresses: "10.0.1.182",
    public_addresses: "18.145.164.132",
    public_addresses: "13.57.237.117",
    public_addresses: "52.53.18.191",
    public_addresses: "13.56.197.7",
    client_addresses: "52.53.27.163",
    num_replicas: 1,
}
regions: {
    addresses: "10.0.1.238",
    addresses: "10.0.1.57",
    addresses: "10.0.1.30",
    addresses: "10.0.1.253",
    public_addresses: "18.144.243.22",
    public_addresses: "18.145.244.49",
    public_addresses: "13.57.177.84",
    public_addresses: "54.183.185.4",
    client_addresses: "18.145.67.119",
    num_replicas: 1,
}
regions: {
    addresses: "10.0.1.242",
    addresses: "10.0.1.230",
    addresses: "10.0.1.133",
    addresses: "10.0.1.134",
    public_addresses: "54.67.163.167",
    public_addresses: "18.145.100.149",
    public_addresses: "54.67.142.60",
    public_addresses: "18.145.181.239",
    client_addresses: "13.56.11.163",
    num_replicas: 1,
}
regions: {
    addresses: "10.0.1.96",
    addresses: "10.0.1.123",
    addresses: "10.0.1.144",
    addresses: "10.0.1.117",
    public_addresses: "52.53.14.185",
    public_addresses: "13.56.189.24",
    public_addresses: "18.145.247.7",
    public_addresses: "52.53.9.106",
    client_addresses: "18.145.106.218",
    num_replicas: 1,
}
regions: {
    addresses: "10.0.1.48",
    addresses: "10.0.1.243",
    addresses: "10.0.1.22",
    addresses: "10.0.1.165",
    public_addresses: "18.145.25.49",
    public_addresses: "18.145.152.235",
    public_addresses: "18.145.128.98",
    public_addresses: "18.145.208.72",
    client_addresses: "54.176.17.255",
    num_replicas: 1,
}
regions: {
    addresses: "10.0.1.191",
    addresses: "10.0.1.254",
    addresses: "10.0.1.58",
    addresses: "10.0.1.128",
    public_addresses: "54.67.133.68",
    public_addresses: "18.145.230.253",
    public_addresses: "184.72.5.129",
    public_addresses: "18.145.12.123",
    client_addresses: "54.177.95.25",
    num_replicas: 1,
}
regions: {
    addresses: "10.0.1.127",
    addresses: "10.0.1.81",
    addresses: "10.0.1.227",
    addresses: "10.0.1.69",
    public_addresses: "18.145.57.120",
    public_addresses: "18.145.213.201",
    public_addresses: "3.101.31.197",
    public_addresses: "54.215.185.93",
    client_addresses: "18.145.245.133",
    num_replicas: 1,
}

broker_ports: 2020
server_port: 2021
forwarder_port: 2022
sequencer_port: 2023

simple_partitioning {
    num_records: 100000000
    record_size_bytes: 100
}

mh_orderer_batch_duration: 5
forwarder_batch_duration: 1
sequencer_batch_duration: 5
sequencer_batch_size: 100
sequencer_rrr: true
replication_factor: 1

# Forwarder
bypass_mh_orderer: false

# Scheduler
num_workers: 3

num_log_managers: 2
num_partitions: 4

enabled_events: ALL

# TCP buffer setting (for large latency deployments)
broker_rcvbuf: 10485760
long_sender_sndbuf: 10485760
